//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par ColorizingDMD.rc
//
#define IDC_MYICON                      2
#define IDD_COLORIZINGDMD_DIALOG        102
#define IDR_ACCEL                       133
#define IDB_PNG9                        168
#define IDB_PNG1                        172
#define IDB_COLM                        172
#define IDI_ICON1                       181
#define IDI_ICON4                       187
#define IDD_COLDLG                      190
#define IDD_TOOLBOX                     190
#define IDD_LISTITEMS                   191
#define IDI_ICON2                       193
#define IDI_ICON3                       209
#define IDD_DETSPR                      209
#define IDI_ICON5                       212
#define IDI_ICON7                       215
#define IDC_CURSOR1                     233
#define IDI_ICON6                       240
#define IDI_ICON8                       243
#define IDI_ICON9                       246
#define IDI_ICON11                      250
#define IDI_ICON10                      255
#define IDI_OPEN                        258
#define IDI_SAVE                        259
#define IDI_CROM                        260
#define IDI_OPENCDUMP                   261
#define IDI_ADDCDUMP                    262
#define IDI_DELFRAME                    263
#define IDI_MOVEFRAME                   264
#define IDI_VPMPATH                     265
#define IDI_ADDCROM                     266
#define IDI_ICON12                      267
#define IDI_ADDTXT                      267
#define IDI_OPENTXT                     268
#define IDD_CHECKDEL                    269
#define IDC_COLMODE2                    1001
#define IDC_NEW                         1001
#define IDC_COLMODE3                    1002
#define IDC_ADDTXT                      1002
#define IDC_COLMODE4                    1003
#define IDC_OPEN                        1003
#define IDC_COLMODE5                    1004
#define IDC_SAVE                        1004
#define IDC_COLMODE6                    1005
#define IDC_UNDO                        1005
#define IDC_COLMODE7                    1006
#define IDC_REDO                        1006
#define IDC_COLMODE8                    1007
#define IDC_HASHMODE                    1007
#define IDC_COLMODE9                    1008
#define IDC_COMPMASK                    1008
#define IDC_COLMODE10                   1009
#define IDC_MOVMASK                     1009
#define IDC_ORGMODE                     1011
#define IDC_DELFRAMES                   1011
#define IDC_CMID                        1012
#define IDC_DRAWPOINT                   1012
#define IDC_MOVEFRAMES                  1012
#define IDC_MMID                        1013
#define IDC_DRAWLINE                    1013
#define IDC_VPMPATH                     1013
#define IDC_DRAWRECT                    1014
#define IDC_OPENCDUMP                   1014
#define IDC_COMBO1                      1015
#define IDC_DRAWCIRC                    1015
#define IDC_ADDCDUMP                    1015
#define IDC_FILL                        1016
#define IDC_OPENCROM                    1016
#define IDC_COPY                        1017
#define IDC_SAVECROM                    1017
#define IDC_COLSET                      1018
#define IDC_ADDCROM                     1018
#define IDC_DRAWPOINT2                  1019
#define IDC_COPYCOLS                    1019
#define IDC_PASTE                       1020
#define IDC_OPENTXT                     1020
#define IDC_PASTE2                      1021
#define IDC_DYNACOLSET                  1023
#define IDC_COLPICK                     1024
#define IDC_COL1SET1                    1036
#define IDC_COL4SET8                    1037
#define IDC_COL1SET2                    1041
#define IDC_4COLMODE2                   1041
#define IDC_FILLED                      1045
#define IDC_CHECKFRAMES                 1049
#define IDC_SELSAMEFR                   1050
#define IDC_NOSETCOL                    1051
#define IDC_CHANGECOLSET                1052
#define IDC_STRY5                       1057
#define IDC_STRY1                       1057
#define IDC_STRY6                       1058
#define IDC_STRY7                       1059
#define IDC_STRY8                       1060
#define IDC_STRY9                       1061
#define IDC_STRY10                      1062
#define IDC_STRY11                      1063
#define IDC_STRY13                      1064
#define IDC_COLTODYNA                   1065
#define IDC_SECTIONLIST2                1066
#define IDC_DELSECTION                  1067
#define IDC_ADDSECTION                  1068
#define IDC_SECTIONNAME                 1069
#define IDC_VPATH                       1069
#define IDC_COPYCOLS2                   1070
#define IDC_1COLMODE                    1071
#define IDC_4COLMODE                    1072
#define IDC_GRADMODE                    1073
#define IDC_GRADMODEB                   1074
#define IDC_COL1                        1075
#define IDC_COL2                        1076
#define IDC_COL3                        1077
#define IDC_COL4                        1078
#define IDC_COL5                        1079
#define IDC_COL6                        1080
#define IDC_COL7                        1081
#define IDC_COL8                        1082
#define IDC_COL9                        1083
#define IDC_COL10                       1084
#define IDC_COL11                       1085
#define IDC_COL12                       1086
#define IDC_COL13                       1087
#define IDC_COL14                       1088
#define IDC_COL15                       1089
#define IDC_COL16                       1090
#define IDC_DYNACOL1                    1091
#define IDC_DYNACOL2                    1092
#define IDC_DYNACOL3                    1093
#define IDC_DYNACOL4                    1094
#define IDC_DYNACOL5                    1095
#define IDC_DYNACOL6                    1096
#define IDC_ISDWORD                     1096
#define IDC_DELSPR                      1096
#define IDC_DYNACOL7                    1097
#define IDC_DYNACOL8                    1098
#define IDC_DYNACOL9                    1099
#define IDC_DYNACOL10                   1100
#define IDC_DYNACOL11                   1101
#define IDC_DYNACOL12                   1102
#define IDC_DYNACOL13                   1103
#define IDC_DYNACOL14                   1104
#define IDC_DYNACOL15                   1105
#define IDC_DYNACOL16                   1106
#define IDC_ADDSECTION2                 1107
#define IDC_STRY15                      1107
#define IDC_INVERTSEL2                  1108
#define IDC_MOVESECTION                 1109
#define IDC_STRY16                      1110
#define IDC_SPRITELIST2                 1111
#define IDC_ADDSPRITE2                  1112
#define IDC_DELSPRITE2                  1113
#define IDC_BUTTON1                     1114
#define IDC_COLROT                      1114
#define IDC_BUTTON                      1114
#define IDC_LIST1                       1115
#define IDC_IDENTIFYDYN                 1115
#define IDC_IDENT                       1115
#define IDC_BUTTON2                     1115
#define IDC_LIST                        1115
#define IDC_LISTSEC                     1115
#define IDC_INVERTSEL3                  1117
#define IDC_LIST2                       1118
#define IDC_LISTSPR                     1118
#define IDC_DELALL                      1119
#define IDC_CANCEL                      1120
#define IDC_DELFREE                     1121
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        270
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
